project_id = "uuspgufbumdmvjolxwug"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template_name = ""

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
s3_enabled = false

[edge_functions]
enabled = true
port = 54324

[functions.admin-login]
verify_jwt = false

[functions.get-orcamentos]
verify_jwt = false