// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuspgufbumdmvjolxwug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1c3BndWZidW1kbXZqb2x4d3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTE1MTIsImV4cCI6MjA2OTgyNzUxMn0.9rHre4rn5BoztmWdIj91OS2_oap7iLUHNQetRIZNWto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});